[programs.localnet]
solana_escrow = "B4BcAjTneKrCi6Gs9XabBeAGisu5GwTWAjPmYWgFCo2A"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/Users/yashmoondhra/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
